[package]
name = "procedural-towns"
version = "0.1.0"
authors = ["Jakob <jakobfischer93@gmail.com>"]
edition = "2018"

[dependencies]

log = "0.4"
env_logger = "0.6"
chrono = "0.4"
rand = "0.6"
regex = "1.1"
lazy_static = "1.2"